services:
  - docker

before_install:
  - docker pull stronglytyped/arm-none-eabi-gcc

script:
  - cd firmware/ && docker run -v$(pwd):/src stronglytyped/arm-none-eabi-gcc /bin/bash -c "make -C /src -j4"
