services:
  - docker

install:
  - sudo apt-get install -y build-essential git bzip2 wget
  - mkdir /work && cd /work && wget -qO- https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2 | tar -xj
  - export PATH="/work/gcc-arm-none-eabi-9-2019-q4-major/bin:$PATH"

script:
  - cd firmware/ && make all
